spring.data.mongodb.uri=mongodb+srv://asifsekh117_db_user:EnJkqnV44jxs77bT@frauddetec0.f4rh6ry.mongodb.net/fraud_inference?appName=frauddetec0
spring.application.name=fraud-backend
management.endpoints.web.exposure.include=health,info,metrics
management.health.mongo.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.mongo.MongoHealthContributorAutoConfiguration
server.port=${PORT:8080}